[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
[tool.setuptools.packages.find]
where = ["."]

[project]
name = "FunctionController"
version = "1.0.2"
description = "Function flow control decorators and runtime execution engine"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
authors = [
    { name = "Tyrel Miguel" }
]

dependencies = []

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
"Documentation" = "https://functioncontrollerdocs.netlify.app"
"Homepage" = "https://tyrel.onrender.com/function-controller"
"Source" = "https://github.com/TyrelGomez/FunctionFlow"
"Official Tech Site" = "https://tyrel.onrender.com"
"Bug Tracker" = "https://github.com/TyrelGomez/FunctionFlow/issues"